apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: pcf-check
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: pcf-check
    apps.tanzu.vmware.com/has-tests: true
spec:
  source:
    git:
      url: https://github.com/elle-durkin/pcf-check.git
      ref:
        branch: aks-test
  build:
    env:
      - name: "BP_MAVEN_BUILD_ARGUMENTS"
        value: "-X package"
  params:
    - name: annotations
      value:
        serving.knative.dev/rollout-duration: 380s
        autoscaling.knative.dev/minScale: "1"
